#!/usr/bin/env bash
# Rased — one-command installer for the CENTRAL node.
# First run: creates .env with random secrets (asks only for the server IP).
# Every run: builds & starts the stack. Safe to re-run.
#
#   bash scripts/install.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

say()  { printf '\033[1;36m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m%s\033[0m\n' "$*"; }

# 1) Prerequisites ------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  warn "Docker is not installed. Install it, then re-run this script:"
  echo "  curl -fsSL https://get.docker.com | sh"
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  warn "The 'docker compose' plugin is missing. Install 'docker-compose-plugin' and retry."
  exit 1
fi

rand()      { openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
detect_ip() { hostname -I 2>/dev/null | awk '{print $1}'; }

# 2) Generate .env on first run ----------------------------------------------
if [ ! -f .env ]; then
  say "First run — creating .env"
  DEF_IP="$(detect_ip)"; DEF_IP="${DEF_IP:-192.168.1.10}"
  read -r -p "Server IP [${DEF_IP}]: " IP || true;  IP="${IP:-$DEF_IP}"
  read -r -p "UPS (NUT) host/IP (Enter to skip): " NUTH || true
  UPSN="ups"
  if [ -n "${NUTH:-}" ]; then read -r -p "UPS name [ups]: " UPSN || true; UPSN="${UPSN:-ups}"; fi

  {
    echo "# Rased CENTRAL node — generated by install.sh. Keep these secrets stable."
    echo "RASED_HOST_ID=central"
    echo "RASED_HOST_NAME=My Server"
    echo "RASED_PUBLIC_BASE_URL=http://${IP}:8002"
    echo "RASED_CORS_ORIGINS=http://${IP}:8082,http://localhost:8082"
    echo "JWT_SECRET=$(rand)"
    echo "ENCRYPTION_KEY=$(rand)"
    echo "AGENT_TOKEN=$(rand)"
    echo "NUT_HOST=${NUTH:-host.docker.internal}"
    echo "NUT_PORT=3493"
    echo "NUT_UPS_NAME=${UPSN}"
  } > .env
  say "Wrote .env with random secrets."
else
  say ".env already exists — keeping your secrets."
fi

# 3) Permissions for the prebuilt UI (nginx uid 101 must read it) ------------
if [ -f web/dist/index.html ]; then
  chmod -R a+rX web/dist 2>/dev/null || true
else
  warn "web/dist not found — build the UI first:  cd web && npm install && npm run build"
fi

# 4) Start --------------------------------------------------------------------
say "Building & starting Rased (first build can take a few minutes)..."
docker compose up -d --build
docker compose up -d --force-recreate rased-ui >/dev/null 2>&1 || true

URL="$(grep -E '^RASED_PUBLIC_BASE_URL=' .env | cut -d= -f2-)"
HOSTPART="$(printf '%s' "${URL:-http://localhost:8002}" | sed -E 's#https?://([^:/]+).*#\1#')"
echo ""
say "Done!"
echo "  Dashboard : http://${HOSTPART}:8082"
echo "  API docs  : http://${HOSTPART}:8002/docs"
echo "  The FIRST account you register becomes the admin."
